---
key_name: devos-tokyo-test-key
region: ap-northeast-1
image: ami-01748a72bed07727c
sec_group: sg-0acbda0211358279c
vpc_subnet_id: subnet-04f433c265d67c2b6
instance_name: [JISEON]Provisioning-instance-in-group_vars
